# Generated by Django 2.2.7 on 2019-11-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='follower',
            field=models.ManyToManyField(blank=True, to='twitterclone.TwitterUser'),
        ),
    ]
