# Generated by Django 2.2.7 on 2019-11-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='name',
        ),
    ]
