# Generated by Django 2.2.7 on 2019-11-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_remove_twitteruser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='follower',
            new_name='following',
        ),
    ]
